name: Deploy Node API (Cloud Run)

on:
  push:
    branches: [ main ]
    paths:
      - "server.js"
      - "package*.json"
      - "Dockerfile"
      - ".github/workflows/deploy-node.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy node-api to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: node-api
          region: ${{ secrets.GCP_REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          source: .
          allow_unauthenticated: true
