name: Deploy Frontend (Firebase Hosting)

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "public/**"
      - "index.html"
      - "vite.config.*"
      - "package*.json"
      - "firebase.json"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Build frontend (with CHATBOT API URL)
        run: npm run build
        env:
          VITE_CHATBOT_API_URL: ${{ secrets.CHATBOT_API_URL }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
